version: "3.8"
services:
  database:
    image: postgres:15.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=$DBNAME
      - POSTGRES_PASSWORD=$DBPASS
    ports:
      - "$DBPORT:5432"
    volumes:
      - db_volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-h", "localhost", "-p", "5432"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - backend
volumes:
  db_volume:
    driver: local
networks:
  backend:
